security:
  oauth2:
    client:
      clientId: ${app_clientId}
      clientSecret: ${app_clientSecret}
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
spring:
  thymeleaf:
    cache: false
  messages:
    basename: messages/messages
    cache-seconds: -1
    encoding: UTF-8
management:
  endpoints:
    web:
      exposure:
        include: "*"
