security:
  oauth2:
    client:
      clientId: 1063849431273-hee3lbstuh3fg54ij66kh4guj4uve6ho.apps.googleusercontent.com
      clientSecret: 2G6ZEom0_xgZX0zXaqzPmLHk
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
