spring:
  application:
    name: ${springboot.app.name:titti-springboot}
  thymeleaf:
    cache: false
  messages:
    basename: messages/messages
    cache-seconds: -1
    encoding: UTF-8

security:
  oauth2:
    client:
      clientId: ${app_clientId}
      clientSecret: ${app_clientSecret}
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
    healthcheck:
      enabled: true
