spring:
  application:
    name: ${springboot.app.name:zuul-router-balancer}
  security:
    oauth2:
      client:
        registration:   
          google:   
            client-id: ${app_clientId}
            client-secret: ${app_clientSecret}

server:
  port: 8100

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${REGISTRY_URL}/eureka
    healthcheck:
      enabled: true
  instance:
#    preferIpAddress: false
    leaseRenewalIntervalInSeconds: 10

logging:
  level:
    com:
      netflix:
        eureka: INFO
        discovery: OFF
    org:
      springframework:
        cloud:
          netflix: trace
zuul:
  debug:
    request: true