spring:
  application:
    name: ${springboot.app.name:turbine-health}

server:
  port: 8110

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${REGISTRY_URL}/eureka
    healthcheck:
      enabled: true
  instance:
#    preferIpAddress: false
    leaseRenewalIntervalInSeconds: 10

logging:
  level:
    com:
      netflix:
        eureka: DEBUG
#        discovery: OFF
    org:
      springframework:
        cloud:
          netflix: trace