spring:
  application:
    name: ${springboot.app.name:eureka-serviceregistry}

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${server.port}/eureka/

logging:
  level:
    com:
      netflix:
        eureka: INFO
        discovery: OFF