server:
     port: 8090
spring:
  application:
    name: ${springboot.app.name:titti-springboot}
  messages:
    basename: messages/messages
    cache-duration: -1
    encoding: UTF-8
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry_host:localhost}:${registry_port:8761}/eureka
    healthcheck:
      enabled: true
