spring:
  application:
    name: ${springboot.app.name:titti-FE}
  thymeleaf:
    cache: false
  messages:
    basename: messages/messages
    cache-duration: -1
    encoding: UTF-8
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  security:
    oauth2:
      client:
        registration:   
          google:   
            client-id: ${app_clientId}
            client-secret: ${app_clientSecret}

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_URL}/eureka
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

feign:
  client:
    config:
      default:
        loggerLevel: FULL